### PR TITLE
Add spout modules

### PR DESCRIPTION
**Pull request by joreg**
for now needs alpha34.103 as it depends on new nodes that come with it. those will be included with beta35

### CODE REVIEW

**Comment by mrvux** [comment]
This https://github.com/mrvux/dx11-vvvv-girlpower/pull/44/commits/f5c1d7b046af750192e797daad0a2233ba46c3bd 
has nothing to do here.

 same as https://github.com/mrvux/dx11-vvvv-girlpower/pull/44/commits/01ddb235b4e373c8b03a36dc3eb8e827dafb005e

Also not gonna merge for alpha version yet, since plan for dx11 build is to still support 33.7 for now

**Comment by pussinboot** [comment]
does this fix the issue where you needed to replace spoutreceiver nodes each time you opened a patch?

**Comment by joreg** [comment]
sorry my bad. i branched off the wrong commit. will resubmit again.

**Comment by joreg** [comment]
@pussinboot  not sure what you mean?! but probably it does not fix anything that is texturesharing-related.

**Comment by pussinboot** [comment]
https://vvvv.org/forum/fromsharedtexture-%28dx11%29-bug?#comment-217441
i get the same behavior using the spoutreceiver node included in the vvvv templates when you install spout, so i guess it is texturesharing related

**Comment by joreg** [comment]
ja, i am afraid this doesn't touch anything related to that problem.

**Pull request closed without merging**
