### PR TITLE
adding modules for Spout support

### PR DESCRIPTION
**Pull request by joreg**
for now needs alpha34.103 as it depends on new nodes that come with it. those will be included with beta35

### CODE REVIEW

**Comment by mrvux** [comment]
Couple of things:
1/Really could run that in current beta, makes 0 sense to force an alpha upgrade to use it.
2/Design is rather fragile,would be much nicer to have a version without having to pass handles around (double->long->double can be lossy)
3/Sender is not good like that, should be a presenter plugin in order to properly use render path instead of early render as it it now

**Comment by joreg** [comment]
/1 yes, only the new plugins are in the alpha already. so i am totally fine with this getting merged only when a beta build comes out. or you decide to also start an alpha branch..
/2 i know you had the same reservation regarding the long handle with the texture-sharing before. i haven't seen it fail so far. can you show a case where it doesn't work?
/3 can you elaborate on that? what is a "presenter plugin"?

**Comment by mrvux** [comment]
1/Well for now the plan is to support 33.7, and there's 0 technical requirement to move to a new alpha/beta. Bit of a pain to force an alpha just for a new node....
2/It's rare but can happen, I've seen lossy issues with handles as doubles. So it  has a very low probability, but it still can, which means it will, and generally when you really need it the least eg : deadline)
3/Using ToSharedTexture with handle out causes early render, so should have a plugin that works "as" a render window instead (so the internal graph is not early cut), and really don't even need to show the handle at all except for debug.

**Comment by joreg** [comment]
2/ the lossy issues i've seen were only when it was not implemented correctly. now i'd argue it is. but happy to be proven wrong. because of course if we have a case that does not work this has to be fixed.

3/if this stops you from accepting this PR that is fine with me. you can close it then, as i'm afraid i won't have the time to tackle this anytime soon.

**Pull request closed without merging**
